var GAME_LEVELS = [
  ["                                                                                                ",
   " x                                                                                              ",
   " x@                                                                                             ",
   " x                                                                                              ",
   " x                         o                                                                    ",
   " x                        xxx                                                                   ",
   " x                                                                             x   x            ",
   " x                                              o                              x o x            ",
   " xxxx          oo                               x                              xxxxx            ",
   " xxxx          xx              xxxxxxxx         x                                               ",
   " x                                              x                                       xxx     ",
   " x                                              x                                               ",
   " x                                              x                                               ",
   " x         xxxx                xxxxxxxxxxxxxxxxxx                                               ",
   " x                                                                              xxxx            ",
   " x                                                                                              ",
   " x o                                                                                            ",
   " xxxxxxxxxxxx    xxxxxxxxxxxxxx                          xxxxxxxxxxxxxxxxx        xxxxxxxxxxxxxx",
   " x          x    x            x                          x               x        x             ",
   " x          x    x            x!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!x             ",
   " x          x!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!x             ",
   " x          x!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!x             ",
   " x          x!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!!!!x             "],
   

  
  ["                  x!!!!!x                                                                                    ",
   "                  xxxxxxx                                                                                  ",
   "                   xvvvx                                                                                   ",
   "  @ o                                                                                                     ",
   "  xxx                                                                                                         ",
   "                                                                                                           ",
   "      xx                                                                                                   ",
   "       xx                                                                                                  ",
   "        xx                                                                                                 ",
   "         xx                                                                                                ",
   "          xx                                                                                               ",
   "           xx                                                                                              ",
   "            xx                                                                                             ",
   "             xxxxxx                                                                                        ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                             o                                                                             ",   
   "                          xxxxxxx                                                                          ",
   "                                        xx                                                                 ",
   "                                         xx                                                                ",
   "                                          xx                                                               ",
   "                                           xx                                                              ",
   "                                            xx                                                             ",
   "                                                   xxxxxxx                                                 ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                  x^^x                                                    o                ",  
   "                    xxx           xxxx                                                    x       o        ",
   "                                                              xxxxxx                             xxx       ",
   "                                                                                     o                     ",
   "                                                                          xx        xx                     ",
   "                                                                         xx                                ",
   "                                                                        xx                                 ",
   "                                                                       xx                                  ",
   "                                                                      xx                                   ",
   "                                                                     xx                x^x                 ",
   "                                                                    xx        x^x      xxx     x^x         ",
   "                                                                   xx         xxx              xx          ",
   "                                                                  xx                                       ",
   "                                                         o                                                 ",
   "                                                       xxxxxxxxx                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                      xxxxxxxxx                                                                            ",
   "                                                                                                           ",
   "              o                                                                                            ",
   "              xx                               xxx                                                         ",
   "                                 xxxx                                                                      ",
   "                                                                                                           ",
   "                                                                   x                                       ",
   "                                         xx                                                                ",
   "                                          xx                                                               ",
   "                                           xx                                                              ",
   "                                            xx                                                             ",
   "                                             xx                                                            ",
   "                                              xx                                                           ",
   "                                               xx                                                          ",
   "                                                                                                           ",
   "                                                       xxxx                                                ",
   "                  x           x         x                                                                 ",
   "                                                  o                                                        ",
   "                                                 xx                                                        ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                         xxx                                               ",
   "                                                           xx                                              ",
   "                                                            xx                                             ",
   "                                                             xx                                            ",
   "                                                              xx            o                              ",
   "                                                                           xxx                             ",
   "                                                                                                           ",
   "                                                                   xxxxx                                   ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "                                                                                                           ",
   "               xx       xx        xx        xx      xxxxxxx                                                ",
   "                                                                                                           ",
   "   oo                                                                                                      ",
   "   oo                                                                                                      ",
   "xxxxxxxxxxx      x^x         x^x       x^x       x^x                                                       ",
   "                 xxx         xxx       xxx       xxx                                                       "],  
  
  
  
  
  
  
  
  
  
  
  
  
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
